lesnictwo_user_users:
    resource: "@LesnictwoUserBundle/Resources/config/routing/uzytkownik.yml"
    prefix:   /users

lesnictwo_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: LesnictwoUserBundle:Default:index }
