lesnictwo_mapa:
    resource: "@LesnictwoMapaBundle/Resources/config/routing.yml"
    prefix:   /

lesnictwo_main:
    resource: "@LesnictwoMainBundle/Resources/config/routing.yml"
    prefix:   /

lesnictwo_user:
    resource: "@LesnictwoUserBundle/Resources/config/routing.yml"
    prefix:   /


